image: moussavdb/yildiz-build-image

pipelines:
  default:
    - step:
        script:
          - openssl aes-256-cbc -pass pass:$OPENSSL_PWD -in private-key.gpg.enc -out private-key.gpg -d
          - gpg --import private-key.gpg
          - mvn -V -B -s settings.xml deploy
          - mvn -V -B -s settings.xml -Pnative-sonar -Denv=linux64 org.jacoco:jacoco-maven-plugin:prepare-agent deploy sonar:sonar -Dsonar.host.url=https://sonarqube.com -Dsonar.login=$SONAR -Dsonar.cfamily.build-wrapper-output=target/sonar-cpp
          - mvn -V -B -s settings.xml -Pnative -Denv=win32 deploy
          - curl -sSL https://download.sourceclear.com/ci.sh | bash