image: moussavdb/yildiz-build-env

pipelines:
  default:
    - step:
        script:
          - openssl aes-256-cbc -pass pass:$OPENSSL_PWD -in private-key.gpg.enc -out private-key.gpg -d
          - gpg --import private-key.gpg
          - mvn -V -B -s settings.xml deploy
          - mvn -V -B -s settings.xml -Denv=linux64 org.jacoco:jacoco-maven-plugin:prepare-agent deploy sonar:sonar -Dsonar.host.url=https://sonarqube.com -Dsonar.login=$SONAR
          - mvn -V -B -s settings.xml -Denv=win32 deploy