image: maven:3.3.9-jdk-8

pipelines:
  default:
    - step:
        script:
          - mvn -V -B -s settings.xml -Denv=linux64 -Dsonar.cfamily.build-wrapper-output.bypass=true org.jacoco:jacoco-maven-plugin:prepare-agent deploy sonar:sonar -Dsonar.host.url=https://sonarqube.com -Dsonar.login=$SONAR
          - mvn -V -B -s settings.xml -Denv=win64 deploy