mkdir src/main/scripts/bullet/build
cd src/main/scripts/bullet/build


cmake ../ -DCMAKE_CXX_FLAGS="-fPIC" -DCMAKE_C_FLAGS="-fPIC" -DBUILD_BULLET3=OFF -DBUILD_CPU_DEMOS=OFF -DBUILD_BULLET2_DEMOS=OFF -DBUILD_EXTRAS=ON -DBUILD_UNIT_TESTS=OFF -DCMAKE_BUILD_TYPE=Release -DCMAKE_COLOR_MAKEFILE=on -DINSTALL_EXTRA_LIBS=on -DINSTALL_LIBS=on -DINTERNAL_UPDATE_SERIALIZATION_STRUCTURES=off -DUSE_CUSTOM_VECTOR_MATH=off -DUSE_DOUBLE_PRECISION=off -DCMAKE_INSTALL_PREFIX="../release/linux64/" -DINCLUDE_INSTALL_DIR="../release/linux64/include" -DLIBRARY_OUTPUT_PATH="" -DLIB_DESTINATION="" -G "Unix Makefiles"

make install
make clean

rm -R *



